ofc legacy packages causing issues

diff --git a/botpanel/catbot-ipc-web-panel-main/scripts/ns-inet b/botpanel/catbot-ipc-web-panel-main/scripts/ns-inet
--- a/botpanel/catbot-ipc-web-panel-main/scripts/ns-inet
+++ b/botpanel/catbot-ipc-web-panel-main/scripts/ns-inet
@@ -4,40 +4,57 @@
 
 botid=$1
 
+get_default_interface() {
+    ip -o -4 route show default 2>/dev/null | awk '
+        {
+            for (i = 1; i <= NF; i++) {
+                if ($i == "dev" && (i + 1) <= NF) {
+                    print $(i + 1)
+                    exit
+                }
+            }
+        }'
+}
+
 NS="catbotns$botid"
 VETH="veth$botid"
 VPEER="vpeer$botid"
 VETH_ADDR="10.200.$botid.1"
 VPEER_ADDR="10.200.$botid.2"
-INTERFACE=$(route -n | grep '^0\.0\.0\.0' | grep -o '[^ ]*$' | head -1)
+INTERFACE="$(get_default_interface)"
 
 if [[ $EUID -ne 0 ]]; then
     echo "You must be root to run this script"
     exit 1
 fi
 
+if [[ -z "$INTERFACE" ]]; then
+    echo "Could not find default network interface with ip route" >&2
+    exit 1
+fi
+
 # Remove namespace if it exists.
-ip netns del $NS &>/dev/null
+ip netns del "$NS" &>/dev/null
 ip link del ${VETH} &>/dev/null
 
 # Create namespace
-ip netns add $NS
+ip netns add "$NS"
 
 # Create veth link.
 ip link add ${VETH} type veth peer name ${VPEER}
 
 # Add peer-1 to NS.
-ip link set ${VPEER} netns $NS
+ip link set ${VPEER} netns "$NS"
 
 # Setup IP address of ${VETH}.
 ip addr add ${VETH_ADDR}/24 dev ${VETH}
 ip link set ${VETH} up
 
 # Setup IP ${VPEER}.
-ip netns exec $NS ip addr add ${VPEER_ADDR}/24 dev ${VPEER}
-ip netns exec $NS ip link set ${VPEER} up
-ip netns exec $NS ip link set lo up
-ip netns exec $NS ip route add default via ${VETH_ADDR}
+ip netns exec "$NS" ip addr add ${VPEER_ADDR}/24 dev ${VPEER}
+ip netns exec "$NS" ip link set ${VPEER} up
+ip netns exec "$NS" ip link set lo up
+ip netns exec "$NS" ip route add default via ${VETH_ADDR}
 
 # Enable IP-forwarding.
 echo 1 > /proc/sys/net/ipv4/ip_forward
